name: stock_manager
description: A simple stock management app

# Ensure you have the latest version of Flutter
dependencies:
  flutter:
    sdk: flutter
environment:
  sdk: '>=3.7.0-0 <4.0.0'
  # Ajoutez d'autres dépendances si nécessaire
  # Par exemple, si vous utilisez une base de données ou des bibliothèques externes, ajoutez-les ici.

dev_dependencies:
  flutter_test:
    sdk: flutter

# Pour utiliser le flutter, l'option suivante est recommandée
flutter:
  uses-material-design: true
